name: Build and Push Image
on:
  workflow_run:     
    workflows: [Publish new release]
    types:
      - completed

defaults:
  run:
    shell: bash -leo pipefail {0}

jobs:
  build-push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo '${{ toJSON(github.event.workflow_run) }}'
