name: Publish new release
on:
  push:
  # schedule:
  #   - cron: '*/5 * * * *'

jobs:
  check-release:
    name: Check release
    uses: dysnix/github-workflows/.github/workflows/upstream.new-release.yaml@upstream-release
    with:
      upstream: cloudflare/wrangler
      version-regex: ^v\d+

  build:
    name: Docker Image
    uses: dysnix/github-workflows/.github/workflows/docker.build-and-push.yaml@upstream-release
    needs: [check-release]
    if: ${{ needs.check-release.outputs.publish }}
    with:
      ## Unconditionally push fresh releases
      push: true
      username: services1dysnix
      version: ${{ needs.check-release.outputs.version }}-r1
    secrets:
      password: "${{ secrets.DOCKERHUB_TOKEN }}"

  publish:
    name: Publish release
    runs-on: ubuntu-latest
    needs: [check-release]
    steps:
      - run: |
          echo 'version: ${{ needs.check-release.outputs.version }}'
          echo 'publish: ${{ needs.check-release.outputs.publish }}'
