name: Publish new release
on:
  schedule:
    - cron: '43 */8 * * *'

jobs:
  check-release:
    name: Check release
    uses: dysnix/github-workflows/.github/workflows/upstream.new-release.yaml@main
    with:
      upstream: cloudflare/wrangler
      version-regex: ^v\d+

  publish:
    name: Publish release
    runs-on: ubuntu-latest
    needs: [check-release]
    steps:
      -
        name: Publish new release
        uses: ncipollo/release-action@v1
        if: ${{ needs.check-release.outputs.publish }}
        with:
          commit: main
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ needs.check-release.outputs.version }}
          body: |
            new upstream release ${{ needs.check-release.outputs.version }}
